#NAME: Tanzeela Khan
#EMAIL: tanzeelakhan@g.ucla.edu
#ID: 204577214

CC=gcc
CFLAGS = -g

all:
	@gcc -g lab1a.c -o lab1a


clean:
	@rm -f lab1a *.txt *.tar.gz

dist: 
	@tar -czvf lab1a-204577214.tar.gz Makefile lab1a.c README