#NAME: Tanzeela Khan
#EMAIL: tanzeelakhan@g.ucla.edu
#ID: 204577214

CC=gcc
CFLAGS = -g

all:
	@gcc -g -pthread lab2_add.c -o lab2_add


clean:
	@rm -f lab2_add *.txt *.tar.gz

dist: 
	@tar -czvf lab2a-204577214.tar.gz Makefile lab1a.c README
