#Name: Tanzeela Khan
#EMAIL: tanzeelakhan@g.ucla.edu
#ID: 204577214


build:
	gcc -lmraa -lm -g -o lab4b lab4b.c

check:
	./lab4b --scale=C

clean:

	@rm -f lab4b *.txt *.tar.gzw

dist:
	@tar -zcvf lab4b-204577214.tar.gz lab4b lab4b.c Makefile README
